spring.application.name=smartstock

app.client-id = ${APP_CLIENT_ID:ABC}
app.client-secret = ${APP_CLIENT_SECRET:DEF}

api.auth-url = http://localhost:3000
api.purchase-sector-url = http://localhost:3000

spring.datasource.url=jdbc:mysql://localhost:3306/stockly?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${BANCOKEY}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
